name: OSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "32 5 * * 1"
  workflow_dispatch:

permissions:
  security-events: write
  id-token: write
  contents: read
  actions: read

jobs:
  analysis:
    name: scorecard-analysis
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run analysis
        id: scorecard
        uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
